### ISSUE TITLE
An item with the same key has already been added. Key: 3d10e529-9b0b-7353-2ef6-39f4eba425d5

### ISSUE THREAD

**Issue by XuJin186** [EasyAbp/Abp.RelatedDtoLoader#20]
An exception occurs in line 122 of the RelatedDtoLoader class: An item with the same key has already been added. Key: 3d10e529-9b0b-7353-2ef6-39f4eba425d5, after debugging, it is found that the value of the Dictionary key is duplicated, so idsToLoad should be deduplicated,
I changed the code to the following to be normal
`var idsToLoad = keyProviderWithIds.Values.Where(x => x != null).Distinct().ToArray();`
Hope your team can solve and update   
Thank you

**Comment by gdlcf88** [comment]
Thanks for feedback, we will check it.

**Comment by LryBackinblack** [comment]
same problem

**Comment by gdlcf88** [comment]
@itryan  Can you check it?

**Comment by XuJin186** [comment]
Will this open source library be maintained?

**Comment by tekix** [comment]
@XuJin186 thanks

**Comment by XuJin186** [comment]
@itryan  @gdlcf88      Hello, the Nuget package has not been updated. May I ask if your team has an exchange group? I would also like to contribute together

**Comment by gdlcf88** [comment]
Hi @itryan, I think the **Github action** is broken.

**Comment by gdlcf88** [comment]
> May I ask if your team has an exchange group? I would also like to contribute together

EasyAbp org needs more people, welcome to PR or contribute your modules

**Comment by XuJin186** [comment]
@gdlcf88  Is there any place for communication, such as QQ group

**Comment by gdlcf88** [comment]
😄 Please email me: gdlcf88@outlook.com

**Comment by XuJin186** [comment]
@gdlcf88   Has been sent
