### ISSUE TITLE
AbpRelatedDtoLoaderAbstractionsModule does not exist...

### ISSUE THREAD

**Issue by Znow** [EasyAbp/Abp.RelatedDtoLoader#21]

**Comment by gdlcf88** [comment]
The module class has been removed in the commit: https://github.com/EasyAbp/Abp.RelatedDtoLoader/commit/69618d9bc11d0d8bda4612bd919b2e5df46a269d#diff-8c62b29952c3a8fa950067732ce42456, so it is not a module anymore but a normal library.

Maybe it was changed for easier use.

**Comment by Znow** [comment]
Then the documentation should be updated also :) It is not working out of the box when reading the documentation.

Thanks in advance
